services:
  web:
    image: nginx
    volumes:
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - 80:80
    restart: always
    depends_on:
      - php
      - db
  php:
    build: docker
    restart: always
    volumes:
      - ./local.env:/var/www/html/local.env
      - ./src:/var/www/html
  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
